import { DetectionRule } from '../types/index.js';

export const EXTENDED_RULES: DetectionRule[] = [
  {
    id: "1password-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\bA3-[A-Z0-9]{6}-(?:(?:[A-Z0-9]{11})|(?:[A-Z0-9]{6}-[A-Z0-9]{5}))-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\\b", "g"),
    keywords: ["a3-"],
    minEntropy: 3.8,
    requiresEntropy: true,
  },
  {
    id: "1password-service-account-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("ops_eyJ[a-zA-Z0-9+/]{250,}={0,3}", "g"),
    keywords: ["ops_"],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "adafruit-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:adafruit)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["adafruit"],
  },
  {
    id: "adobe-client-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:adobe)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["adobe"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "age-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}", "g"),
    keywords: ["age-secret-key-1"],
  },
  {
    id: "airtable-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:airtable)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{17})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["airtable"],
  },
  {
    id: "airtable-personnal-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(pat[[:alnum:]]{14}\\.[a-f0-9]{64})\\b", "g"),
    keywords: ["airtable"],
  },
  {
    id: "algolia-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:algolia)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["algolia"],
  },
  {
    id: "alibaba-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:alibaba)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["alibaba"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "anthropic-admin-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(sk-ant-admin01-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["sk-ant-admin01"],
  },
  {
    id: "anthropic-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(sk-ant-api03-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["sk-ant-api03"],
  },
  {
    id: "artifactory-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\bAKCp[A-Za-z0-9]{69}\\b", "g"),
    keywords: ["akcp"],
    minEntropy: 4.5,
    requiresEntropy: true,
  },
  {
    id: "artifactory-reference-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\bcmVmd[A-Za-z0-9]{59}\\b", "g"),
    keywords: ["cmvmd"],
    minEntropy: 4.5,
    requiresEntropy: true,
  },
  {
    id: "asana-client-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:asana)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["asana"],
  },
  {
    id: "asana-client-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:asana)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["asana"],
  },
  {
    id: "aws-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b((?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16})\\b", "g"),
    keywords: ["a3t", "akia", "asia", "abia", "acca"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "aws-amazon-bedrock-api-key-long-lived",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(ABSK[A-Za-z0-9+/]{109,269}={0,2})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["absk"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "aws-amazon-bedrock-api-key-short-lived",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29t", "g"), // gitleak-radar:ignore aws-amazon-bedrock-api-key-short-lived
    keywords: ["bedrock-api-key-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "azure-ad-client-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("(?:^|[\\\\'\"\\x60\\s>=:(,)])([a-zA-Z0-9_~.]{3}\\dQ~[a-zA-Z0-9_~.-]{31,34})(?:$|[\\\\'\"\\x60\\s<),])", "g"),
    keywords: ["q~"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "beamer-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:beamer)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(b_[a-z0-9=_\\-]{44})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["beamer"],
  },
  {
    id: "bitbucket-client-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:bitbucket)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["bitbucket"],
  },
  {
    id: "bitbucket-client-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:bitbucket)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["bitbucket"],
  },
  {
    id: "bittrex-access-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:bittrex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["bittrex"],
  },
  {
    id: "bittrex-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:bittrex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["bittrex"],
  },
  {
    id: "clickhouse-cloud-api-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(4b1d[A-Za-z0-9]{38})\\b", "g"),
    keywords: ["4b1d"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "clojars-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("CLOJARS_[a-z0-9]{60}", "gi"),
    keywords: ["clojars_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "cloudflare-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:cloudflare)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["cloudflare"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "cloudflare-global-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:cloudflare)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{37})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["cloudflare"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "cloudflare-origin-ca-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(v1\\.0-[a-f0-9]{24}-[a-f0-9]{146})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["cloudflare", "v1.0-"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "codecov-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:codecov)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["codecov"],
  },
  {
    id: "coinbase-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:coinbase)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["coinbase"],
  },
  {
    id: "confluent-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:confluent)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["confluent"],
  },
  {
    id: "confluent-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:confluent)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["confluent"],
  },
  {
    id: "contentful-delivery-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:contentful)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{43})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["contentful"],
  },
  {
    id: "curl-auth-user",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\bcurl\\b(?:.*|.*(?:[\\r\\n]{1,2}.*){1,5})[ \\t\\n\\r](?:-u|--user)(?:=|[ \\t]{0,5})(\"(:[^\"]{3,}|[^:\"]{3,}:|[^:\"]{3,}:[^\"]{3,})\"|'([^:']{3,}:[^']{3,})'|((?:\"[^\"]{3,}\"|'[^']{3,}'|[\\w$@.-]+):(?:\"[^\"]{3,}\"|'[^']{3,}'|[\\w${}@.-]+)))(?:\\s|$)", "g"),
    keywords: ["curl"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "databricks-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(dapi[a-f0-9]{32}(?:-\\d)?)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["dapi"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "datadog-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:datadog)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["datadog"],
  },
  {
    id: "defined-networking-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:dnkey)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(dnkey-[a-z0-9=_\\-]{26}-[a-z0-9=_\\-]{52})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["dnkey"],
  },
  {
    id: "digitalocean-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(doo_v1_[a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["doo_v1_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "digitalocean-pat",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(dop_v1_[a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["dop_v1_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "digitalocean-refresh-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(dor_v1_[a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["dor_v1_"],
  },
  {
    id: "discord-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:discord)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["discord"],
  },
  {
    id: "discord-client-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:discord)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9]{18})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["discord"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "discord-client-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:discord)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["discord"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "droneci-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:droneci)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["droneci"],
  },
  {
    id: "dropbox-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{15})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["dropbox"],
  },
  {
    id: "dropbox-long-lived-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\\-_=]{43})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["dropbox"],
  },
  {
    id: "dropbox-short-lived-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(sl\\.[a-z0-9\\-=_]{135})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["dropbox"],
  },
  {
    id: "facebook-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(\\d{15,16}(\\||%)[0-9a-z\\-_]{27,40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["facebook"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "facebook-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:facebook)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["facebook"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "fastly-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:fastly)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["fastly"],
  },
  {
    id: "finicity-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["finicity"],
  },
  {
    id: "finicity-client-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["finicity"],
  },
  {
    id: "finnhub-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:finnhub)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["finnhub"],
  },
  {
    id: "flickr-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:flickr)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["flickr"],
  },
  {
    id: "flyio-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b((?:fo1_[\\w-]{43}|fm1[ar]_[a-zA-Z0-9+\\/]{100,}={0,3}|fm2_[a-zA-Z0-9+\\/]{100,}={0,3}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["fo1_", "fm1", "fm2_"],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "freemius-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\"']secret_key[\"']\\s*=>\\s*[\"'](sk_[\\S]{29})[\"']", "gi"),
    keywords: ["secret_key"],
  },
  {
    id: "freshbooks-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:freshbooks)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["freshbooks"],
  },
  {
    id: "gcp-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(AIza[\\w-]{35})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["aiza"],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "github-app-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("(?:ghu|ghs)_[0-9a-zA-Z]{36}", "g"),
    keywords: ["ghu_", "ghs_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "github-fine-grained-pat",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("github_pat_\\w{82}", "g"),
    keywords: ["github_pat_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "github-oauth",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("gho_[0-9a-zA-Z]{36}", "g"),
    keywords: ["gho_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "github-pat",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("ghp_[0-9a-zA-Z]{36}", "g"),
    keywords: ["ghp_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "github-refresh-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("ghr_[0-9a-zA-Z]{36}", "g"),
    keywords: ["ghr_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-cicd-job-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("glcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}", "g"),
    keywords: ["glcbt-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-deploy-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("gldt-[0-9a-zA-Z_\\-]{20}", "g"),
    keywords: ["gldt-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-feature-flag-client-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("glffct-[0-9a-zA-Z_\\-]{20}", "g"),
    keywords: ["glffct-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-feed-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("glft-[0-9a-zA-Z_\\-]{20}", "g"),
    keywords: ["glft-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-incoming-mail-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("glimt-[0-9a-zA-Z_\\-]{25}", "g"),
    keywords: ["glimt-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-kubernetes-agent-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("glagent-[0-9a-zA-Z_\\-]{50}", "g"),
    keywords: ["glagent-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-oauth-app-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("gloas-[0-9a-zA-Z_\\-]{64}", "g"),
    keywords: ["gloas-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-pat",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("glpat-[\\w-]{20}", "g"),
    keywords: ["glpat-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-pat-routable",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\bglpat-[0-9a-zA-Z_-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b", "g"),
    keywords: ["glpat-"],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "gitlab-ptt",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("glptt-[0-9a-f]{40}", "g"),
    keywords: ["glptt-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-rrt",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("GR1348941[\\w-]{20}", "g"),
    keywords: ["gr1348941"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-runner-authentication-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("glrt-[0-9a-zA-Z_\\-]{20}", "g"),
    keywords: ["glrt-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-runner-authentication-token-routable",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\bglrt-t\\d_[0-9a-zA-Z_\\-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b", "g"),
    keywords: ["glrt-"],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "gitlab-scim-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("glsoat-[0-9a-zA-Z_\\-]{20}", "g"),
    keywords: ["glsoat-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitlab-session-cookie",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("_gitlab_session=[0-9a-z]{32}", "g"),
    keywords: ["_gitlab_session="],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "gitter-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:gitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["gitter"],
  },
  {
    id: "grafana-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(eyJrIjoi[A-Za-z0-9]{70,400}={0,3})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["eyjrijoi"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "grafana-cloud-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(glc_[A-Za-z0-9+/]{32,400}={0,3})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["glc_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "grafana-service-account-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["glsa_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "harness-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("(?:pat|sat)\\.[a-zA-Z0-9_-]{22}\\.[a-zA-Z0-9]{24}\\.[a-zA-Z0-9]{20}", "g"),
    keywords: ["pat.", "sat."],
  },
  {
    id: "hashicorp-tf-password",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:administrator_login_password|password)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(\"[a-z0-9=_\\-]{8,20}\")(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["administrator_login_password", "password"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "heroku-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:heroku)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["heroku"],
  },
  {
    id: "heroku-api-key-v2",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b((HRKU-AA[0-9a-zA-Z_-]{58}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["hrku-aa"],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "hubspot-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:hubspot)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["hubspot"],
  },
  {
    id: "infracost-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(ico-[a-zA-Z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["ico-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "intercom-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:intercom)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{60})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["intercom"],
  },
  {
    id: "jfrog-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{73})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["jfrog", "artifactory", "bintray", "xray"],
  },
  {
    id: "jfrog-identity-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["jfrog", "artifactory", "bintray", "xray"],
  },
  {
    id: "jwt",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(ey[a-zA-Z0-9]{17,}\\.ey[a-zA-Z0-9\\/\\\\_-]{17,}\\.(?:[a-zA-Z0-9\\/\\\\_-]{10,}={0,2})?)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["ey"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "kraken-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:kraken)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9\\/=_\\+\\-]{80,90})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["kraken"],
  },
  {
    id: "kucoin-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:kucoin)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{24})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["kucoin"],
  },
  {
    id: "kucoin-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:kucoin)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["kucoin"],
  },
  {
    id: "launchdarkly-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:launchdarkly)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["launchdarkly"],
  },
  {
    id: "linear-client-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:linear)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["linear"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "linkedin-client-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:linked[_-]?in)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{14})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["linkedin", "linked_in", "linked-in"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "linkedin-client-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:linked[_-]?in)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["linkedin", "linked_in", "linked-in"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "lob-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:lob)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}((live|test)_[a-f0-9]{35})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["test_", "live_"],
  },
  {
    id: "lob-pub-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:lob)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}((test|live)_pub_[a-f0-9]{31})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["test_pub", "live_pub", "_pub"],
  },
  {
    id: "looker-client-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:looker)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["looker"],
  },
  {
    id: "looker-client-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:looker)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["looker"],
  },
  {
    id: "mailchimp-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:MailchimpSDK.initialize|mailchimp)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32}-us\\d\\d)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["mailchimp"],
  },
  {
    id: "mailgun-private-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(key-[a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["mailgun"],
  },
  {
    id: "mailgun-pub-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(pubkey-[a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["mailgun"],
  },
  {
    id: "mailgun-signing-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["mailgun"],
  },
  {
    id: "mapbox-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:mapbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(pk\\.[a-z0-9]{60}\\.[a-z0-9]{22})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["mapbox"],
  },
  {
    id: "mattermost-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:mattermost)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{26})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["mattermost"],
  },
  {
    id: "maxmind-license-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b([A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["_mmk"],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "messagebird-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:message[_-]?bird)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{25})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["messagebird", "message-bird", "message_bird"],
  },
  {
    id: "messagebird-client-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:message[_-]?bird)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["messagebird", "message-bird", "message_bird"],
  },
  {
    id: "microsoft-teams-webhook",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("https://[a-z0-9]+\\.webhook\\.office\\.com/webhookb2/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}@[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}/IncomingWebhook/[a-z0-9]{32}/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}", "g"),
    keywords: ["webhook.office.com", "webhookb2", "incomingwebhook"],
  },
  {
    id: "netlify-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:netlify)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{40,46})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["netlify"],
  },
  {
    id: "new-relic-browser-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(NRJS-[a-f0-9]{19})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["nrjs-"],
  },
  {
    id: "new-relic-insert-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(NRII-[a-z0-9-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["nrii-"],
  },
  {
    id: "new-relic-user-api-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["new-relic", "newrelic", "new_relic"],
  },
  {
    id: "new-relic-user-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(NRAK-[a-z0-9]{27})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["nrak"],
  },
  {
    id: "notion-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(ntn_[0-9]{11}[A-Za-z0-9]{32}[A-Za-z0-9]{3})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["ntn_"],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "npm-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(npm_[a-z0-9]{36})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["npm_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "nuget-config-password",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("<add key=\\\"(?:(?:ClearText)?Password)\\\"\\s*value=\\\"(.{8,})\\\"\\s*/>", "gi"),
    keywords: ["<add key="],
    minEntropy: 1,
    requiresEntropy: true,
  },
  {
    id: "nytimes-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:nytimes|new-york-times,|newyorktimes)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["nytimes", "new-york-times", "newyorktimes"],
  },
  {
    id: "octopus-deploy-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(API-[A-Z0-9]{26})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["api-"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "openai-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(sk-(?:proj|svcacct|admin)-(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})T3BlbkFJ(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})\\b|sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["t3blbkfj"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "openshift-user-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(sha256~[\\w-]{43})(?:[^\\w-]|$)", "g"),
    keywords: ["sha256~"],
    minEntropy: 3.5,
    requiresEntropy: true,
  },
  {
    id: "perplexity-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(pplx-[a-zA-Z0-9]{48})(?:[\\x60'\"\\s;]|\\\\[nr]|$|\\b)", "g"),
    keywords: ["pplx-"],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "plaid-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(access-(?:sandbox|development|production)-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["plaid"],
  },
  {
    id: "plaid-client-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["plaid"],
    minEntropy: 3.5,
    requiresEntropy: true,
  },
  {
    id: "plaid-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["plaid"],
    minEntropy: 3.5,
    requiresEntropy: true,
  },
  {
    id: "planetscale-oauth-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(pscale_oauth_[\\w=\\.-]{32,64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["pscale_oauth_"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "prefect-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(pnu_[a-zA-Z0-9]{36})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["pnu_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "private-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----[\\s\\S-]{64,}?KEY(?: BLOCK)?-----", "gi"),
    keywords: ["-----begin"],
  },
  {
    id: "pulumi-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(pul-[a-f0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["pul-"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "pypi-upload-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("pypi-AgEIcHlwaS5vcmc[\\w-]{50,1000}", "g"),
    keywords: ["pypi-ageichlwas5vcmc"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "rapidapi-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:rapidapi)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{50})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["rapidapi"],
  },
  {
    id: "readme-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(rdme_[a-z0-9]{70})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["rdme_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "rubygems-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(rubygems_[a-f0-9]{48})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["rubygems_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "scalingo-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(tk-us-[\\w-]{48})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["tk-us-"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "sendbird-access-id",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:sendbird)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["sendbird"],
  },
  {
    id: "sendbird-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:sendbird)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["sendbird"],
  },
  {
    id: "sentry-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:sentry)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["sentry"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "sentry-org-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\bsntrys_eyJpYXQiO[a-zA-Z0-9+/]{10,200}(?:LCJyZWdpb25fdXJs|InJlZ2lvbl91cmwi|cmVnaW9uX3VybCI6)[a-zA-Z0-9+/]{10,200}={0,2}_[a-zA-Z0-9+/]{43}(?:[^a-zA-Z0-9+/]|$)", "g"),
    keywords: ["sntrys_eyjpyxqio"],
    minEntropy: 4.5,
    requiresEntropy: true,
  },
  {
    id: "sentry-user-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(sntryu_[a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["sntryu_"],
    minEntropy: 3.5,
    requiresEntropy: true,
  },
  {
    id: "settlemint-application-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(sm_aat_[a-zA-Z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["sm_aat"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "settlemint-personal-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(sm_pat_[a-zA-Z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["sm_pat"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "settlemint-service-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(sm_sat_[a-zA-Z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["sm_sat"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "shippo-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(shippo_(?:live|test)_[a-fA-F0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["shippo_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "shopify-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("shpat_[a-fA-F0-9]{32}", "g"),
    keywords: ["shpat_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "shopify-custom-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("shpca_[a-fA-F0-9]{32}", "g"),
    keywords: ["shpca_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "shopify-private-app-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("shppa_[a-fA-F0-9]{32}", "g"),
    keywords: ["shppa_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "shopify-shared-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("shpss_[a-fA-F0-9]{32}", "g"),
    keywords: ["shpss_"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "sidekiq-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:BUNDLE_ENTERPRISE__CONTRIBSYS__COM|BUNDLE_GEMS__CONTRIBSYS__COM)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{8}:[a-f0-9]{8})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["bundle_enterprise__contribsys__com", "bundle_gems__contribsys__com"],
  },
  {
    id: "sidekiq-sensitive-url",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\bhttps?://([a-f0-9]{8}:[a-f0-9]{8})@(?:gems.contribsys.com|enterprise.contribsys.com)(?:[\\/|\\#|\\?|:]|$)", "gi"),
    keywords: ["gems.contribsys.com", "enterprise.contribsys.com"],
  },
  {
    id: "slack-app-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("xapp-\\d-[A-Z0-9]+-\\d+-[a-z0-9]+", "gi"),
    keywords: ["xapp"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "slack-bot-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("xoxb-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*", "g"),
    keywords: ["xoxb"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "slack-config-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("xoxe.xox[bp]-\\d-[A-Z0-9]{163,166}", "gi"),
    keywords: ["xoxe.xoxb-", "xoxe.xoxp-"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "slack-config-refresh-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("xoxe-\\d-[A-Z0-9]{146}", "gi"),
    keywords: ["xoxe-"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "slack-legacy-bot-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("xoxb-[0-9]{8,14}-[a-zA-Z0-9]{18,26}", "g"),
    keywords: ["xoxb"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "slack-legacy-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("xox[os]-\\d+-\\d+-\\d+-[a-fA-F\\d]+", "g"),
    keywords: ["xoxo", "xoxs"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "slack-legacy-workspace-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("xox[ar]-(?:\\d-)?[0-9a-zA-Z]{8,48}", "g"),
    keywords: ["xoxa", "xoxr"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "slack-user-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("xox[pe](?:-[0-9]{10,13}){3}-[a-zA-Z0-9-]{28,34}", "g"),
    keywords: ["xoxp-", "xoxe-"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "slack-webhook-url",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("(?:https?://)?hooks.slack.com/(?:services|workflows|triggers)/[A-Za-z0-9+/]{43,56}", "g"),
    keywords: ["hooks.slack.com"],
  },
  {
    id: "snyk-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:snyk[_.-]?(?:(?:api|oauth)[_.-]?)?(?:key|token))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["snyk"],
  },
  {
    id: "sonar-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:sonar[_.-]?(login|token))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}((?:squ_|sqp_|sqa_)?[a-z0-9=_\\-]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["sonar"],
  },
  {
    id: "sourcegraph-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(\\b(sgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40}|sgp_[a-fA-F0-9]{40}|[a-fA-F0-9]{40})\\b)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["sgp_", "sourcegraph"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "square-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b((?:EAAA|sq0atp-)[\\w-]{22,60})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["sq0atp-", "eaaa"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "squarespace-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:squarespace)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["squarespace"],
  },
  {
    id: "stripe-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b((?:sk|rk)_(?:test|live|prod)_[a-zA-Z0-9]{10,99})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["sk_test", "sk_live", "sk_prod", "rk_test", "rk_live", "rk_prod"],
    minEntropy: 2,
    requiresEntropy: true,
  },
  {
    id: "travisci-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:travis)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{22})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["travis"],
  },
  {
    id: "twilio-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("SK[0-9a-fA-F]{32}", "g"),
    keywords: ["sk"],
    minEntropy: 3,
    requiresEntropy: true,
  },
  {
    id: "twitch-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:twitch)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["twitch"],
  },
  {
    id: "twitter-access-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{45})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["twitter"],
  },
  {
    id: "twitter-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9]{15,25}-[a-zA-Z0-9]{20,40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["twitter"],
  },
  {
    id: "twitter-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{25})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["twitter"],
  },
  {
    id: "twitter-api-secret",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{50})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["twitter"],
  },
  {
    id: "twitter-bearer-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(A{22}[a-zA-Z0-9%]{80,100})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["twitter"],
  },
  {
    id: "typeform-api-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:typeform)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(tfp_[a-z0-9\\-_\\.=]{59})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["tfp_"],
  },
  {
    id: "vault-batch-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("\\b(hvb\\.[\\w-]{138,300})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "g"),
    keywords: ["hvb."],
    minEntropy: 4,
    requiresEntropy: true,
  },
  {
    id: "yandex-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(t1\\.[A-Z0-9a-z_-]+[=]{0,2}\\.[A-Z0-9a-z_-]{86}[=]{0,2})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["yandex"],
  },
  {
    id: "yandex-api-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(AQVN[A-Za-z0-9_\\-]{35,38})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["yandex"],
  },
  {
    id: "yandex-aws-access-token",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(YC[a-zA-Z0-9_\\-]{38})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["yandex"],
  },
  {
    id: "zendesk-secret-key",
    name: undefined,
    description: "Auto-generated rule",
    severity: "high",
    pattern: new RegExp("[\\w.-]{0,50}?(?:zendesk)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", "gi"),
    keywords: ["zendesk"],
  },
  {
    id: "generic-header-token",
    name: "Generic Header Context Key",
    description: "Detects generic Custom-Token and X-Auth-Token headers with high entropy keys.",
    severity: "high",
    pattern: new RegExp("(?:X-[A-Za-z0-9\\-]+-(?:Token|Key|Secret)|Authorization|Bearer)\\s*[:=]\\s*(?:\"|'|`|Bearer\\s+)?([A-Za-z0-9_\\-]{32,})", "gi"),
    keywords: ["x-", "-token", "-key", "-secret", "authorization", "bearer"],
    minEntropy: 3.5,
    requiresEntropy: true
  },
  {
    id: "weak-hardcoded-password",
    name: "Weak Environmental Password",
    description: "Detects notoriously weak hardcoded passwords assigned to variables, circumventing entropy filters.",
    severity: "medium",
    pattern: new RegExp("(?:password|pwd|pass)(?:'|\"|\\s|:|=)*(admin|root|123456|password|qwerty)", "gi"),
    keywords: ["password", "pwd", "pass", "admin", "root", "123456", "qwerty"],
    requiresEntropy: false
  },
  {
    id: "split-secret-concatenation",
    name: "Concatenated Static Secret",
    description: "Detects secrets physically split across concatenated string bounds to evade basic heuristics.",
    severity: "high",
    pattern: new RegExp("(?:ghp_|glpat-|sk_live_|AIza|xoxb-)[\\w\\-]*['\"]\\s*\\+\\s*['\"][\\w\\-]{15,}", "gi"),
    keywords: ["ghp_", "glpat-", "sk_live_", "aiza", "xoxb-"],
    requiresEntropy: false
  }
];
